name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test runner
        run: |
          # Extract version from tag and create version file
          echo "${GITHUB_REF#refs/tags/}" > VERSION.txt
          # make test build the test-runner and run tests
          make test

      # ğŸ·ï¸ create the release for this tag and upload the artifact
      - name: Publish release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/test-runner.com
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') }}
